# Generated by Django 4.2 on 2023-05-08 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webstore', '0009_alter_products_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
