# Generated by Django 4.2 on 2023-05-10 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webstore', '0011_alter_products_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
