# Generated by Django 4.2 on 2023-05-13 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webstore', '0012_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
