# Generated by Django 4.2.2 on 2023-06-15 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webstore', '0014_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='https://placehold.co/600x400?text=Catagory', upload_to='images/'),
        ),
    ]
